/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PreProcess;
import controller.Weka;

/**
 *
 * @author mfahry
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    PreProcess preprocess;
    Weka wk;
    public Home() {
        preprocess = new PreProcess();
        wk = new Weka();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDataSet = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNaiveBayes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMultinomial = new javax.swing.JTextArea();
        btnStopWords = new javax.swing.JButton();
        btnPunc = new javax.swing.JButton();
        btnStem = new javax.swing.JButton();
        btnClassify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDataSet.setColumns(20);
        txtDataSet.setRows(5);
        jScrollPane1.setViewportView(txtDataSet);

        txtNaiveBayes.setColumns(20);
        txtNaiveBayes.setRows(5);
        jScrollPane2.setViewportView(txtNaiveBayes);

        txtMultinomial.setColumns(20);
        txtMultinomial.setRows(5);
        jScrollPane3.setViewportView(txtMultinomial);

        btnStopWords.setText("Stop Words");
        btnStopWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopWordsActionPerformed(evt);
            }
        });

        btnPunc.setText("Remove Punc");
        btnPunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuncActionPerformed(evt);
            }
        });

        btnStem.setText("Stemming");
        btnStem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStemActionPerformed(evt);
            }
        });

        btnClassify.setText("Classify");
        btnClassify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassifyActionPerformed(evt);
            }
        });

        jLabel1.setText("Result (Bayesian Network) :");

        jLabel2.setText("Result (Multinomial Naive Bayes) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStopWords)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClassify, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStopWords)
                    .addComponent(btnPunc)
                    .addComponent(btnStem)
                    .addComponent(btnClassify))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopWordsActionPerformed
        // TODO add your handling code here:
        preprocess.stopWords();
    }//GEN-LAST:event_btnStopWordsActionPerformed

    private void btnPuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuncActionPerformed
        // TODO add your handling code here:
        preprocess.cleanPunctuation();
    }//GEN-LAST:event_btnPuncActionPerformed

    private void btnStemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStemActionPerformed
        // TODO add your handling code here:
        preprocess.lowerCaseCorpus();
        preprocess.generateTerms();
        preprocess.saveTerms();
        preprocess.stemming();
    }//GEN-LAST:event_btnStemActionPerformed

    private void btnClassifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassifyActionPerformed
        // TODO add your handling code here:
        wk.generateArff();
        wk.generateFeature();
        wk.classifyUsingNaiveBayes();
        wk.classifyUsingMultinomialNaiveBayes();
        
        txtDataSet.append(wk.getDataArff());
        
        String[] temp;
        
        temp = wk.getResultNaiveBayes();
        for(int i=0; i< temp.length; i++){
            txtNaiveBayes.append(temp[i]);
        }
        
        temp = wk.getResultMultinomial();
        for(int i=0; i< temp.length; i++){
            txtMultinomial.append(temp[i]);
        }
    }//GEN-LAST:event_btnClassifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassify;
    private javax.swing.JButton btnPunc;
    private javax.swing.JButton btnStem;
    private javax.swing.JButton btnStopWords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtDataSet;
    private javax.swing.JTextArea txtMultinomial;
    private javax.swing.JTextArea txtNaiveBayes;
    // End of variables declaration//GEN-END:variables
}
